CREATE DATABASE IF NOT EXISTS app;

GRANT CREATE,DROP,INSERT,DELETE,SELECT,UPDATE ON app.* TO 'dbuser'@'%';

/* for prisma */
GRANT CREATE,ALTER,DROP,REFERENCES ON *.* TO 'dbuser'@'%';

FLUSH PRIVILEGES;
