version: '3'
services:
  node:
    build:
      context: ../..
      dockerfile: ./.docker/images/node/Dockerfile.dev
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    tty: true
    volumes:
      - ../..:/var/www
    env_file:
      - .env.development
    ports:
      - 3000:3000
      - 8000:8000
    networks:
      - dev-net

  mysql:
    platform: linux/x86_64
    build:
      context: ../..
      dockerfile: ./.docker/images/mysql/Dockerfile.dev
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - .env.development
    networks:
      - dev-net

volumes:
  mysql:
    driver: local

networks:
  dev-net:
    driver: bridge
